---
name: Oppdater releases

on:
  push:
    branches:
      - main
    paths:
      - ".github/manifest.yml"

jobs:
  update_repo_vars:
    name: Oppdater repo variabler
    uses: joc-ke/workflows/.github/workflows/update_repo_variable.yml@main
    secrets: inherit
